---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
#clear all variables
rm(list = ls())

# load libraries
library(rio)
library(ggplot2)
library(tidyr)
```

# Load the data

```{r}
# base URL for all the files
repo_url = "https://github.com/FuntamendalsRedwan/FinalHW-E1/raw/refs/heads/main/raw%20data/"

# all the individual file names
files = paste0(repo_url, c("fsi-2006.xlsx","fsi-2007.xlsx","fsi-2008.xlsx","fsi-2009.xlsx","fsi-2010.xlsx","fsi-2011.xlsx","fsi-2012.xlsx","fsi-2013.xlsx","fsi-2014.xlsx","fsi-2015.xlsx","fsi-2016.xlsx","fsi-2017.xlsx","fsi-2018.xlsx","fsi-2019.xlsx","fsi-2020.xlsx","fsi-2021.xlsx","fsi-2022-download.xlsx","FSI-2023-DOWNLOAD.xlsx"))

# put all the data into fsi_data
fsi_data = import_list(files, rbind = TRUE)

# look at the data types and names
str(fsi_data)
```

# Keep only the wanted columns

```{r}
# rename the columns to match the assignment
names(fsi_data)[5:16] = c("C1_Security_Apparatus", "C2_Factionalized_Elites", "C3_Group_Grievance", "E1_Economy", "E2_Economic_Inequality", "E3_Human_Flight_and_Brain_Drain", "P1_State_Legitimacy", "P2_Public_Services", "P3_Human_Rights", "S1_Demographic_Pressures", "S2_Refugees_and_IDPs", "X1_External_Intervention")

#keep only the wanted columns
fsi_clean = fsi_data[, c("Country", "Year", "Rank", "Total", "C1_Security_Apparatus", "C2_Factionalized_Elites", "C3_Group_Grievance", "E1_Economy", "E2_Economic_Inequality", "E3_Human_Flight_and_Brain_Drain", "P1_State_Legitimacy", "P2_Public_Services", "P3_Human_Rights", "S1_Demographic_Pressures", "S2_Refugees_and_IDPs", "X1_External_Intervention")]

# look at the data types
str(fsi_clean)

```

# Clean up the data

```{r}
#clean up the test from Rank
fsi_clean$Rank = as.integer(gsub("[^0-9]", "", fsi_clean$Rank))

# keep only the year in the year column
fsi_clean$Year <- as.integer(format(as.Date(fsi_clean$Year), "%Y"))

# look at the data types
str(fsi_clean)
```


# Plotting Total per year

```{r}
# plot Total per year as a boxplot
ggplot(fsi_clean, aes(x = factor(Year), y = Total)) + geom_boxplot() +
    labs(title = "Total Variable per Year", x = "Year", y = "Total Variable")
```

# Plotting C1, C2, C3

```{r}
# filter the data for years 2013 and 2023
fsi_sub = fsi_clean[fsi_clean$Year %in% c(2013, 2023), ]

# make it into long format for easier plotting
fsi_long = pivot_longer(fsi_sub, cols = c("C1_Security_Apparatus", "C2_Factionalized_Elites", "C3_Group_Grievance"))

# Plot using the default 'value' and 'name' columns created by pivot_longer
ggplot(fsi_long, aes(x = value)) + geom_histogram(bins = 10) +
  facet_grid(Year ~ name) + labs(title="Security Apperatus, Fractionalized Elites, and Group Grievances in 2013 and 2023")

```





